#!/usr/bin/env bash

exists() {
  command -v "$1" >/dev/null 2>&1
}

if ! exists dropbox ; then
  echo "Installing Dropbox..."
  sudo apt install -y nautilus-dropbox
fi

if ! exists git ; then
  echo "Installing git..."
  sudo apt install -y git
fi

if ! exists thefuck ; then
  echo "Install The Fuck..."
  sudo apt install -y python3-dev python3-pip
  sudo pip3 install thefuck
fi

if ! exists vim ; then
  echo "Installing vim..."
  sudo apt install -y vim
fi

if ! exists atom ; then
	echo "Install Atom..."
	wget https://atom.io/download/deb -O atom.deb
	sudo dpkg -i atom.deb
	rm atom.deb
fi

echo "Done!"
